path_to_image: single_app/lonely_feynman.tar
ports: 1111:2222
commands: /bin/bash -c 'sudo apt-get update && sudo apt-get install -y python-pip python-dev build-essential && pip install -r /home/app/requirements.txt && python /home/app/app.py 2222'
